### ISSUE TITLE
Enable i18n

### ISSUE THREAD

**Issue by aahna-ashina** [nation3/wiki#12]
For https://app.dework.xyz/nation3?taskId=99280151-2e56-425c-9732-68839c6e7887

---

- [x] i18n: Add Chinese locale: `zh`
- [x] i18n: Add locale drop-down to navbar
- [x] i18n: Update `README` with information on how to start the Chinese version on localhost (https://github.com/nation3/wiki/pull/13/commits/8076a19803f4c5418f3f540570242913873a6cc3)
- [x] i18n: Translate docs from English to Chinese (copy from ZIP file [uploaded](https://github.com/nation3/wiki/pull/11#issuecomment-1123073771) by @Mosquitochen)
- [x] Chinese: Fix Markdown formatting so that it matches the English docs (https://github.com/nation3/wiki/pull/11/commits/31c26982c1653c6f0f29099ae78ae9d7474b2e2b https://github.com/nation3/wiki/pull/11/commits/31c26982c1653c6f0f29099ae78ae9d7474b2e2b https://github.com/nation3/wiki/pull/11/commits/00a17cdbbec22b26958ba0c0f8deee42e896bcf1 https://github.com/nation3/wiki/pull/11/commits/11f622d4500a2fc56ff5f9f6c2bc4a3446fbd95d https://github.com/nation3/wiki/pull/11/commits/3171955a3cfe3f0085221eea08d28a135c276657)
- [x] Chinese: Review translations and suggest corrections (@Zhaogw)
- [x] Chinese: Translate labels in navbar (https://github.com/nation3/wiki/pull/15/commits/906bdf37bac3619b58669a98fe6de5eca4ef46c2)
- [x] Chinese: Remove `\` from `\$NATION` and `\$veNATION` (https://github.com/nation3/wiki/pull/14/commits/844e62b3ae86f56db92c16d2c36946fb686a5b4d)
- [x] Chinese: Fix wrong link syntax in Chinese docs (https://github.com/nation3/wiki/pull/16/commits/e805f991add4622e94575f9426ffe8b7d4828c59)
- [ ] Chinese: Ask someone the `#🇨🇳-chinese` channel to review all the translated pages

**Comment by aahna-ashina** [comment]
PR: https://github.com/nation3/wiki/pull/11

**Comment by luisivan** [comment]
Perfect @aahna-ashina, let me know when the remaining points are done and we'll mark this task as done :)
